### ISSUE TITLE
Publish the API Docs

### ISSUE THREAD

**Issue by aashutosh-samagra** [Konnect-Agri/tasks#19]
## Description

Documentation must be published for the APIs written in the complete Konnect Stack.

## Tasks
- [ ] API Documentation for
    - [ ] Beckn Based APIs (UFSI)
    - [ ] Consent Manager 
    - [ ] AgriDex
    - [ ] Integration Steps
    - [ ] Architecture of the Stack
    - [ ] Query Resolver
    - [ ] Authorization
